### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes)

### ISSUE THREAD

**Issue by ghostzero** [ghostzero/tmi-cluster#20]
```
[2022-10-18 19:39:38] [94ca50d9] Register cleanup loop for every 530 sec.
[2022-10-18 19:39:40] [94ca50d9] TMI Cluster Client getting evacuated with status code 5...
Channel Distributor: 0 locked channels got unlocked for re-join.
TMI Cluster Client evacuated! Migrated: 0
Got exit signal with code 5
[2022-10-18 19:39:46] Unable to acquire flush stale lock...
[2022-10-18 19:39:50] Reconnecting 93212 disconnected channels...
[2022-10-18 19:40:22] #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('update `tmi_clu...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run('update `tmi_clu...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(509): Illuminate\Database\Connection->affectingStatement('update `tmi_clu...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3281): Illuminate\Database\Connection->update('update `tmi_clu...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(999): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/html/vendor/ghostzero/tmi-cluster/src/Repositories/DatabaseChannelManager.php(61): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /var/www/html/vendor/ghostzero/tmi-cluster/src/Repositories/RedisChannelDistributor.php(56): GhostZero\TmiCluster\Repositories\DatabaseChannelManager->acknowledged(Array)
#7 /var/www/html/vendor/ghostzero/tmi-cluster/src/Repositories/RedisChannelDistributor.php(70): GhostZero\TmiCluster\Repositories\RedisChannelDistributor->joinNow(Array, Array, false)
#8 /var/www/html/vendor/ghostzero/tmi-cluster/src/Repositories/SupervisorRepository.php(61): GhostZero\TmiCluster\Repositories\RedisChannelDistributor->flushStale(Array, Array)
#9 /var/www/html/vendor/ghostzero/tmi-cluster/src/AutoScale.php(78): GhostZero\TmiCluster\Repositories\SupervisorRepository->flushStale()
#10 /var/www/html/vendor/ghostzero/tmi-cluster/src/AutoScale.php(64): GhostZero\TmiCluster\AutoScale->releaseStaleSupervisors(Object(GhostZero\TmiCluster\Supervisor))
#11 /var/www/html/vendor/ghostzero/tmi-cluster/src/Supervisor.php(107): GhostZero\TmiCluster\AutoScale->scale(Object(GhostZero\TmiCluster\Supervisor))
#12 /var/www/html/vendor/ghostzero/tmi-cluster/src/Supervisor.php(78): GhostZero\TmiCluster\Supervisor->autoScale()
#13 /var/www/html/vendor/ghostzero/tmi-cluster/src/Supervisor.php(53): GhostZero\TmiCluster\Supervisor->loop()
#14 /var/www/html/vendor/ghostzero/tmi-cluster/src/Commands/TmiClusterCommand.php(90): GhostZero\TmiCluster\Supervisor->monitor()
#15 /var/www/html/vendor/ghostzero/tmi-cluster/src/Commands/TmiClusterCommand.php(57): GhostZero\TmiCluster\Commands\TmiClusterCommand->start(Object(GhostZero\TmiCluster\Supervisor))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GhostZero\TmiCluster\Commands\TmiClusterCommand->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#22 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 /var/www/html/vendor/symfony/console/Application.php(998): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(GhostZero\TmiCluster\Commands\TmiClusterCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}

In Arr.php line 565:
                                                                               
  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes)                                                                      
                
```

**Comment by ghostzero** [comment]
Addressed in https://github.com/ghostzero/tmi-cluster/commit/6d65ac1e58228368b2ea0a6d4631696815a761f1
